name: coveralls

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number"
        required: true
        type: number

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Print Success Message
        run: |
          echo "This job is so fun for PR #${{ github.event.inputs.pr_number }}!"
