name: This is a good time

on:
  workflow_dispatch:

jobs:
  check-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Create Dynamic Job
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/dynamic_job.yml/dispatches \
            -d '{"ref":"main", "inputs": {"pr_number": "${{ github.event.pull_request.number }}"}}'
