name: This is a good time

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  actions: write
  pull-requests: write

jobs:
  check-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Create Check Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{
              "name": "coveralls/coverage",
              "head_sha": "'"${SHA}"'",
              "status": "completed",
              "conclusion": "success",
              "output": {
                "title": "This is so fun",
                "summary": "This job ran successfully for PR #'"${PR_NUMBER}"'."
              }
            }'
